# GitLab CI configuration for the BookLab project

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  # Make the Google Cloud credentials available to the runner
  - echo $GOOGLE_CLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json
  - export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-service-key.json
  # Allow Gradle cache directory to be cached by GitLab
  - export GRADLE_USER_HOME=`pwd`/.gradle

# Backend jobs
.build:backend(template): &build-backend
  image: gradle:4.7
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - "build"
      - "*/build"
      - ".gradle/caches"
  variables:
    ORG_GRADLE_PROJECT_exclude: "booklab-frontend-android"

build:backend:
  <<: *build-backend
  except:
    - master
    - develop

build:backend(master):
  <<: *build-backend
  script: gradle --build-cache assembleDist dokka
  artifacts:
    expire_in: 1 week
    paths:
      - "*/build/libs"
      - "*/build/dokka"
  only:
    - master
    - develop

.test:backend(template): &test-backend
  image: gradle:4.7
  stage: test
  script: gradle --build-cache check
  coverage: '/booklab:\s*(\d+(?:\.\d+)?%)/'
  dependencies:
    - build:backend
    - build:backend(master)
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "build"
      - "*/build"
      - ".gradle/caches"
  variables:
    ORG_GRADLE_PROJECT_exclude: "booklab-frontend-android"

test:backend:
  <<: *test-backend
  except:
    - master
    - develop

test:backend(master):
  <<: *test-backend
  artifacts:
    expire_in: 1 week
    paths:
      - "*/build/reports"
  only:
    - master
    - develop

# Web frontend jobs
.build:frontend:web(template): &build-frontend-web
  image: node:8
  stage: build
  script:
    - cd booklab-frontend-web
    - npm install
    - npm run build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - "booklab-frontend-web/node_modules"
      - "booklab-frontend-web/build/angular"
  tags:
    - longJob

build:frontend:web:
  <<: *build-frontend-web
  except:
    - master
    - develop

build:frontend:web(master):
  <<: *build-frontend-web
  script:
    - cd booklab-frontend-web
    - npm install
    - npm run build
    - npm run compodoc
  artifacts:
    expire_in: 1 week
    paths:
      - "booklab-frontend-web/build/angular"
      - "booklab-frontend-web/build/docs"
  only:
    - master
    - develop

.test:frontend:web(template): &test-frontend-web
  image: fabianishere/puppeteer-root:1.4.0
  stage: test
  script:
    - cd booklab-frontend-web
    - npm install
    - npm run ng test -- --browsers ChromeCI --code-coverage --watch false
  coverage: '/Branches\s*:\s*(\d+(?:\.\d+)?%)/'
  dependencies:
    - build:frontend:web
    - build:frontend:web(master)
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "booklab-frontend-web/node_modules"
      - "booklab-frontend-web/build/angular"
  tags:
    - longJob

test:frontend:web:
  <<: *test-frontend-web
  except:
    - master
    - develop

test:frontend:web(master):
  <<: *test-frontend-web
  artifacts:
    expire_in: 1 week
    paths:
      - "*/build/reports"
  only:
    - master
    - develop

test:frontend:web:e2e:
  <<: *test-frontend-web
  variables:
    HEADLESS: "TRUE"
  script:
    - cd booklab-frontend-web
    - npm install
    - npm run ng e2e
  allow_failure: true

# Android frontend jobs
.build:frontend:android(template): &build-frontend-android
  image: thyrlian/android-sdk
  stage: build
  script: gradle --build-cache :booklab-frontend-android:assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - "booklab-frontend-android/build"
      - ".gradle/caches"
  tags:
    - longJob

build:frontend:android:
  <<: *build-frontend-android
  except:
    - master

build:frontend:android(master):
  <<: *build-frontend-android
  script: gradle --build-cache :booklab-frontend-android:assemble :booklab-frontend-android:dokka
  artifacts:
    expire_in: 1 week
    paths:
      - "booklab-frontend-android/build/dokka"
  only:
    - master

test:frontend:android:
  image: thyrlian/android-sdk
  stage: test
  script: gradle --build-cache :booklab-frontend-android:check
  dependencies:
    - build:frontend:android
    - build:frontend:android(master)
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "booklab-frontend-android/build"
      - ".gradle/caches"
  tags:
    - longJob
