# This is the Gradle build system for JVM applications
image: openjdk:8-jdk

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - echo $GOOGLE_CLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json
  - export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-service.key.json
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - "*/build"
      - .gradle


test:
  stage: test
  script: ./gradlew check
  coverage: '/booklab:\s*(\d+(?:\.\d+)?%)/'
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - "*/build"
      - .gradle
