# GitLab CI configuration for the BookLab project

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  # Make the Google Cloud credentials available to the runner
  - echo $GOOGLE_CLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > $HOME/gcloud-service-key.json
  - export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-service-key.json
  # Allow Gradle cache directory to be cached by GitLab
  - export GRADLE_USER_HOME=`pwd`/.gradle

# Backend jobs
.build:backend(template): &build-backend
  image: gradle:4.7
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - "build"
      - "*/build"
      - ".gradle/caches"

build:backend:
  <<: *build-backend
  except:
    - master

build:backend(master):
  <<: *build-backend
  script: gradle --build-cache assembleDist dokka
  artifacts:
    expire_in: 1 week
    paths:
      - "*/build/libs"
      - "*/build/dokka"
  only:
    - master

.test:backend(template): &test-backend
  image: gradle:4.7
  stage: test
  script: gradle --build-cache check
  coverage: '/booklab:\s*(\d+(?:\.\d+)?%)/'
  dependencies:
    - build:backend
    - build:backend(master)
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "build"
      - "*/build"
      - ".gradle/caches"

test:backend:
  <<: *test-backend
  except:
    - master

test:backend(master):
  <<: *test-backend
  artifacts:
    expire_in: 1 week
    paths:
      - "*/build/reports"
  only:
    - master

# Frontend jobs
.build:frontend(template): &build-frontend
  image: node:8
  stage: build
  script:
    - cd booklab-frontend
    - npm install
    - npm run build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - "booklab-frontend/node_modules"
      - "booklab-frontend/build/angular"
  tags:
    - longJob

build:frontend:
  <<: *build-frontend
  except:
    - master

build:frontend(master):
  <<: *build-frontend
  script:
    - cd booklab-frontend
    - npm run build
    - npm run compodoc
  artifacts:
    expire_in: 1 week
    paths:
      - "booklab-frontend/build/angular"
      - "booklab-frontend/build/docs"
  only:
    - master

.test:frontend(template): &test-frontend
  image: fabianishere/puppeteer-root:1.4.0
  stage: test
  script:
    - cd booklab-frontend
    - npm install
    - npm run ng test -- --browsers ChromeCI --code-coverage --watch false
  coverage: '/Branches\s*:\s*(\d+(?:\.\d+)?%)/'
  dependencies:
    - build:frontend
    - build:frontend(master)
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - "booklab-frontend/node_modules"
      - "booklab-frontend/build/angular"
  tags:
    - longJob

test:frontend:
  <<: *test-frontend
  except:
    - master

test:frontend(master):
  <<: *test-frontend
  artifacts:
    expire_in: 1 week
    paths:
      - "*/build/reports"
  only:
    - master

test:frontend:e2e:
  <<: *test-frontend
  variables:
    HEADLESS: "TRUE"
  script:
    - cd booklab-frontend
    - npm install
    - npm run ng e2e
  allow_failure: true
