version: "3"
services:
  frontend:
    image: "booklab-frontend:${TAG-1.0}"
    networks:
      - frontend
    restart: on-failure

  backend:
    image: "booklab-deployment-${ENV-production}:${TAG-1.0}"
    networks:
      - backend
    restart: on-failure
    volumes:
      - ./config:/config:ro
    environment:
      - PORT=80
      - ENV=${ENV}
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}

  database:
      image: postgres
      networks:
        - backend
      restart: on-failure
# uncomment in production
#      volumes:
#        - "/data/booklab:/var/lib/postgresql/data"
      environment:
        - POSTGRES_DB=booklab
        - POSTGRES_USER=booklab-backend
        - POSTGRES_PASSWORD=booklabpassword

  proxy:
    image: "booklab-proxy:${TAG-1.0}"
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    restart: on-failure


networks:
  frontend:
  backend:
