version: "3"
services:
  frontend:
    image: "booklab-frontend:${TAG-1.0}"
    networks:
      - frontend
    restart: on-failure

  backend:
    image: "booklab-deployment-${ENV-testing}:${TAG-1.0}"
    networks:
      - backend
    restart: on-failure
    volumes:
      - ./config:/config:ro
    environment:
      - PORT=80
      - ENV=${ENV}

  proxy:
    image: "booklab-proxy:${TAG-1.0}"
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    restart: on-failure


networks:
  frontend:
  backend:
