version: "3"
services:
  frontend:
    image: "booklab-frontend:${TAG-latest}"
    networks:
      - frontend
    restart: on-failure

  backend:
    image: "booklab-backend:${TAG-latest}"
    networks:
      - backend
    restart: on-failure
    volumes:
      - ./config:/config:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/keys.json

  proxy:
    image: "booklab-proxy:${TAG-latest}"
    ports:
      - "80"
    networks:
      - frontend
      - backend
    restart: on-failure


networks:
  frontend:
  backend:
